### ISSUE TITLE
import svn.remote - ImportError: No module named remote

### ISSUE THREAD

**Issue by ManuDevelopia** [dsoprea/PySvn#10]
I have installed in my Ubuntu 14.04 using the next:
```pip install svn```

and I tried the following code:

```python
import svn.remote

r = svn.remote.RemoteClient('https://my.remote.repo/svn')
r.checkout('/tmp/working')
```

And I get the next error

```python
Traceback (most recent call last):
  File "svn.py", line 1, in <module>
    import svn.remote
  File "/home/manu/Desktop/UQASAR/pythonanywhere/snv/svn.py", line 1, in <module>
    import svn.remote
ImportError: No module named remote
```

Maybe I forgot doing something?

Thanks in advance!

**Comment by ManuDevelopia** [comment]
Update: I have tried from the terminal running python and typing all the code and works but if the code is writed in a file does not and returns the "ImportError: No module named remote" error.

**Comment by dsoprea** [comment]
There might be a path error caused by the project that you're calling it
from.

Look at the path from your Python, directly. Example, for Python 2.7:

>>> import sys
>>> import pprint
>>> pprint.pprint(sys.path)
['',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-linux2',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages']
>>> import svn
>>> svn.__file__
'/usr/local/lib/python2.7/dist-packages/svn/__init__.pyc'


Now, look at the path at the point that you're trying to import *svn*.



Dustin

**Comment by ManuDevelopia** [comment]
I'm not using a project, I'm just using a plain file written with Emacs::Jedi text create to test the program. I have also tried in a MabookPro Mavericks installed svn with Brew with the same results using the console. I tried also with pyCharm creating a Django project and it works. 

As you sad this seems to be a path problem.

I've tried also  creating a new pathtest.py file with this content 
```python
import sys
print (sys.path)
```
After executing the output is: 
>['/home/manu/Devel/Workspace/PyCharm/pysvn', 
>'/usr/lib/python2.7', 
>'/usr/lib/python2.7/plat-x86_64-linux-gnu', 
>'/usr/lib/python2.7/lib-tk', 
>'/usr/lib/python2.7/lib-old', 
>'/usr/lib/python2.7/lib-dynload', 
>'/usr/local/lib/python2.7/dist-packages', 
>'/usr/lib/python2.7/dist-packages', 
>'/usr/lib/python2.7/dist-packages/PILcompat', 
>'/usr/lib/python2.7/dist-packages/gtk-2.0', 
>'/usr/lib/pymodules/python2.7', 
>'/usr/lib/python2.7/dist-packages/ubuntu-sso-client']

The path where svn is installed: /usr/local/lib/python2.7/dist-packages is included, so is supposed to be right to support import svn.remote on the code.

I tried other installed modules in the same path and they appear to be working.

Can you provide me a few steps to start working with lib after installing with pip?

Thanks a lot!

**Comment by dsoprea** [comment]
One or more of the path entries before it might be hijacking the import.
Check for old versions of "svn" or other packages having the same name.

Dustin

**Comment by ManuDevelopia** [comment]
Hi again, I´ve tried with a fresh installation of Debian stable and it perfectly works, so as you commented this must be an issue caused by other packages interference, I will try to discover which is causing the problem, if I succeed I will let you know. Thanks again for your support!

**Comment by ManuDevelopia** [comment]
After having a look at the packages installed with pip I cannot see any problem with names so I decided to remove and reinstall using easy_install and this started to work (CLI-interpreter, emacs-jedi, pycharm). Sorry for the inconveniences, I really don't know were the problem was.  Thanks a lot!

**Comment by dsoprea** [comment]
Sure. Good luck, Manu.
