### ISSUE TITLE
Support for Python 3.6?

### ISSUE THREAD

**Issue by iN5iNN3R470R** [dsoprea/PySvn#101]
Is someone working on upgrading to have support for Python 3.6?
If not I can attempt to contribute.

**Comment by dsoprea** [comment]
If you're having issues, please share them.

Of course, submitting the change yourself is always the quickest route. You'll solve your own need as well as potentially solve other peoples'.

**Comment by iN5iNN3R470R** [comment]
My sincere apologies.
I am using pysvn from http://pysvn.tigris.org/, and mistook your repository for it. I'm terribly sorry for the confusion.
