### ISSUE TITLE
UnicodeDecodeError when return is not ASCII

### ISSUE THREAD

**Issue by Dollyn** [dsoprea/PySvn#11]
File "D:\dev\python3\lib\site-packages\svn\common.py", line 52, in run_command
    stdout = stdout.decode('ASCII')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc8 in position 0: ordinal not in range(128)

**Comment by dsoprea** [comment]
Agreed. Sorry for the inconvenience.

**Comment by codyzu** [comment]
This change broke python3 support for me... I added some details by comments (with an idea of how to fix it) to commit c8098a78a5bf7004a4e0ee027f9abccc31d76ce9.

I will try work on this and make a pull request in a few hours.
