### ISSUE TITLE
nose is not required for svn to work but mentioned in install_requires

### ISSUE THREAD

**Issue by daa** [dsoprea/PySvn#111]
It would be better if test requirements were separated from install requirements to not to have to install unnecessary dependencies. And it would be better if ``nose`` requirement moved from ``requirements.txt`` to ``tox.ini`` or ``test-requirements.txt`` for example or otherwise separated from dependencies required for ``svn`` to work.

**Comment by dsully** [comment]
+1 - please remove nose from svn/resources/requirements.txt
