### ISSUE TITLE
svn.exception.SvnException: Command failed; Can't make directory 'url': Permission denied\n"

### ISSUE THREAD

**Issue by arnoldxiao** [dsoprea/PySvn#112]
I did use PySvn like this:

`import svn.remote`

`@staticmethod`
`def checkout():`
`    r = svn.remote.RemoteClient('path', username='username', password='password')`
`    r.checkout('/4.9.5')`

`ClassName.checkout()`

and run it, but it raise an SvnException: Command failed with (1): ['svn', '--non-interactive', '--username', 'username', '--password', 'password', '--no-auth-cache', 'checkout', 'path', '/4.9.5']
b"svn: E000013: Can't make directory '/4.9.5': Permission denied\n"

**Comment by dsoprea** [comment]
You've passed an absolute path and, as the message says, you don't have
permission to create it.

**Comment by arnoldxiao** [comment]
Ok, Thanks, but also did not support for command `svn mkdir` now, right?
