### ISSUE TITLE
local client can not support delete operation.

### ISSUE THREAD

**Issue by EricDoug** [dsoprea/PySvn#116]
It can't delete directory with local client when I want update old files.

**Comment by matt4d617474** [comment]
I also needed this recently, so created a branch.  Will try and get it merged upstream...

**Comment by mistermocha** [comment]
Grepping through code shows there is no delete action. I can't do an `svn delete file/to/be/deleted` with primitives.

I'm sure I can create a raw command to do so, but that gets me further from desired state.

`$ pip freeze | grep -i svn
svn==0.3.46`

**Comment by dsoprea** [comment]
Added in https://github.com/dsoprea/PySvn/commit/0cd50bb9f07d5ca3b26261cb2eb4b4bbabce063e.
