### ISSUE TITLE
"non-existent in revision" When listing recursively

### ISSUE THREAD

**Issue by TylerGubala** [dsoprea/PySvn#139]
Hello,

I have been using your code quite a bit. There seems to be something wrong with the way that the `recursive` option works with the `list_recursive` function however. I am getting a strange error that some of the items attempting to be listed don't exist.

Moreover, the items that are listed are mostly all incorrectly listed as files, not directories. Not sure if it is a bug?

The `svn` repo that I am pulling from is listed here:

https://svn.blender.org/svnroot/bf-blender/tags/blender-2.78-release/lib/

It contains source code for the program Blender 3d.

I am trying to query the directories nested within but get errors almost right away. Here is an example:
```python
>>> from svn.remote import RemoteClient
>>> myclient = RemoteClient("https://svn.blender.org/svnroot/bf-blender/tags/blender-2.78-release/lib/")
>>> for item, info in myclient.list_recursive(): print(item)
```

```
 ... 
darwin-9.x.universal
python
win64
win64_vc12
windows
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\TGubs\Code\Python\bpy-make\venv\3.7-64\lib\site-packages\svn\common.py", line 396, in list_recursive
    for entry in self.list(extended=True, rel_path=current_rel_path):
  File "C:\Users\TGubs\Code\Python\bpy-make\venv\3.7-64\lib\site-packages\svn\common.py", line 344, in list
    do_combine=True)
  File "C:\Users\TGubs\Code\Python\bpy-make\venv\3.7-64\lib\site-packages\svn\common.py", line 54, in run_command
    return self.external_command(cmd, environment=self.__env, **kwargs)
  File "C:\Users\TGubs\Code\Python\bpy-make\venv\3.7-64\lib\site-packages\svn\common_base.py", line 34, in external_command
    p.returncode, cmd, stdout))
svn.exception.SvnException: Command failed with (1): ['svn', '--non-interactive', 'ls', '--xml', 'https://svn.blender.org/svnroot/bf-blender/tags/blender-2.78-release/lib//android\\armv7-a_9']
b'svn: warning: W160013: URL \'https://svn.blender.org/svnroot/bf-blender/tags/blender-2.78-release/lib/android%5Carmv7-a_9\' non-existent in revision 62289\r\n<?xml version="1.0" encoding="UTF-8"?>\r\n<lists>\r\n<list\r\n   path="https://svn.blender.org/svnroot/bf-blender/tags/blender-2.78-release/lib/android%5Carmv7-a_9">\r\n</list>\r\n</lists>\r\nsvn: E200009: Could not list all targets because some targets don\'t exist\r\n'
```

Thanks much in advance!

**Comment by dsoprea** [comment]
I don't know. This is a Subversion problem, not a PySvn problem. If I were you, I'd try to clone it down again and see if you still have the issue.

https://lmgtfy.com/?q=subversion+Could+not+list+all+targets+because+some+targets+don%27t+exist

**Comment by TylerGubala** [comment]
I'm not trying to iterate over a repo I've already cloned; I'm trying to
query an internet repository prior to cloning.

You know, you can post real links on github. They don't have to be "Let Me
Google That For You" links. And considering that I'm asking specifically
about your repository, it stands to reason that I have already looked this
up...

Many of the issues online relate to updating a local working tree, or
adding a new file. All I am trying to do is recursively list the files of
an internet repository. I understand that there are some command line
options, but what is the recommendation when using this repository? Local
cloning really isn't an option, due to the size of the svn repository.

**Comment by dsoprea** [comment]
You're right. I missed that in my quick look.

That repository might've been in a state of transition. It seems fine to me. I ran the same code you did and let it run for eleven minutes before I terminated it. There are a ton of entries.

I added debugging code to print whether each entry is reported as being a directory or file, but they seem fine:

```
entry: [windows_vc14] IS-DIRECTORY? [True]
entry: [armv7-a_9] IS-DIRECTORY? [True]
entry: [cycles] IS-DIRECTORY? [True]
entry: [README] IS-DIRECTORY? [False]
darwin-9.x.universal
entry: [alembic] IS-DIRECTORY? [True]
entry: [boost] IS-DIRECTORY? [True]
entry: [clang-omp-3.5] IS-DIRECTORY? [True]
entry: [ffmpeg] IS-DIRECTORY? [True]
```

Note that you're printing "darwin-9.x.universal" because we're yielding it and then queueing it upon first seeing it. The items before and after are either siblings in the same path or are adjacent in the queue.

**Comment by TylerGubala** [comment]
@dsoprea What OS are you on? 

[Here](https://github.com/dsoprea/PySvn/blob/0c222a9a49b25d1fcfbc170ab9bc54288efe7f49/svn/common.py#L400) you are using `os.path.join` even though on Windows that means that `\\` will change certain characters to control characters through the use of escapes, hence my issue.
