### ISSUE TITLE
Issue with Locale: wc.info() issue with XML on working copy

### ISSUE THREAD

**Issue by the-moog** [dsoprea/PySvn#148]
I have an issue with quering a working copy.  I thought at first it was a verson issue as the older install was on 0.3.46, the newer one on 1.0.1, however that does not appear to be the case.

Same folder.
1: is in a container (Debian based)
2: in the real file system (Ubuntu)
Note: In reality they are the same folders and files!!

What to do to track down the issue?  Being a container I have limited debug, but I'll see if I can hook it up to pycharm.  Any other ideas?

pysvn 1.0.1
Container - Python 3.7.3
Ubuntu - Python 3.7.5

On both
```python
import os
import svn.local
folder = os.path.abspath(".")
wc = svn.local.LocalClient(folder)
info = wc.info()
```

On Ubuntu (redacted) it works as it should.
--
{'url': 'https://server.com/svn/code', 'relative_url': '^/', 'entry#kind': 'dir', 'entry#path': '.', 'entry#revision': 242, 'repository/root': 'https://server.com/svn/code', 'repository/uuid': '32f932b-a1ee-4af7-9410-dbb59f3b4fd8', 'wc-info/wcroot-abspath': '/var/lib/docker/volumes/jenkins/_data/workspace/test1', 'wc-info/schedule': 'normal', 'wc-info/depth': 'infinity', 'commit/author': 'j', 'commit/date': datetime.datetime(2020, 2, 7, 23, 36, 53, 708195, tzinfo=tzutc()), 'commit#revision': 242, 'entry_kind': 'dir', 'entry_path': '.', 'entry_revision': 242, 'repository_root': 'https://server.com/svn/code', 'repository_uuid': '32f932b-a1ee-4af7-9410-dbb59f3b4fd8', 'wcinfo_wcroot_abspath': '/var/lib/docker/volumes/jenkins/_data/workspace/test1', 'wcinfo_schedule': 'normal', 'wcinfo_depth': 'infinity', 'commit_author': 'j', 'commit_date': datetime.datetime(2020, 2, 7, 23, 36, 53, 708195, tzinfo=tzutc()), 'commit_revision': 242}

On Container it breaks inside wc.info()
--
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/svn/common.py", line 82, in info
    root = xml.etree.ElementTree.fromstring(result)
  File "/usr/local/lib/python3.7/xml/etree/ElementTree.py", line 1315, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0

**Comment by the-moog** [comment]
Update:
Connected pycharm (a bit convoluted as it's a remote container in a remote server in another country)
It gets stranger.....
Over pycharm via ssh remote debug as jenkins@server.com it works fine.
Over ssh jenkins@server.com from the container host it works fine.
Over docker shell it breaks
```bash
docker exec -it --user jenkins <containerinstance> /bin/bash
```
It must be sensitive to some user environment that is (or is not) being picked up....

**Comment by the-moog** [comment]
Ok, got it.  It is a bug.
I added a print(return) to the svn invocation in info() member function in common.py and found
svn: warning: cannot set LC_CTYPE locale\nsvn: warning: environment variable LANG is en_US.UTF-8\nsvn: warning: please check that your locale name is correct\n
So, pysvn is not checking the return from the sub-process (which is in error) and trying to convert the above string into XML.  It should detect the error and return gracefully.
Oddly installed svn CLI tools work fine.
Perhaps pysvn should detect the available localle and use a good guess.

**Comment by the-moog** [comment]
Workround (if a bit hacky)
LC_ALL=C python <script>.py
Seems to work in both instances

**Comment by dsoprea** [comment]
We now dump _stderr_ under normal circumstances. We will also curry the value of LANG in the local environment to Subversion on the backend. We will only default to a _specific_ value of LANG if it's not found. I find it distasteful to use environment variables in this context, but that's where the information lives and where it is expected to be.
