### ISSUE TITLE
type str doesn't  support the buffered api split('\n')

### ISSUE THREAD

**Issue by clt-phoenix** [dsoprea/PySvn#15]
I'm using python 3.3,  when I use a RemoteClient to list entries in a repository via file protocol , It reports the error "type str doesn't  support the buffered api split('\n')"

It seems that in this case , the stdout object in run_command function turns to be an bytes object, so  it should be decode to an str object.   So I add " stdout = stdout.decode('utf-8') ", it seems works fine in my case . But I'm not sure does the 'utf-8' suit for all cases.

**Comment by Dreamsorcerer** [comment]
I'm also seeing this in basic use, just trying to perform a checkout (Python 3.4):

>>> import svn.remote
>>> r = svn.remote.RemoteClient("https://plugins.svn.wordpress.org/akismet/trunk")
>>> r.checkout("akismet")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/svn/remote.py", line 20, in checkout
    self.run_command('checkout', cmd)
  File "/usr/local/lib/python3.4/dist-packages/svn/common.py", line 51, in run_command
    return stdout if combine is True else stdout.split("\n")
TypeError: Type str doesn't support the buffer API

**Comment by SanderKleykens** [comment]
Seeing the same problem in Python 3.3 and 3.4.

**Comment by altendky** [comment]
# works
    return stdout if combine is True else stdout.decode().strip('\n').split('\n')
    # does not work
    return stdout if combine is True else stdout.split("\n")

I'm running Python34 in Cygwin.

**Comment by altendky** [comment]
I just patched this in my fork in e4386d0978f08ac75f049ea2a4f47da6cf69d094.

**Comment by dsoprea** [comment]
Sorry for the delay. Thanks for reporting the issue.

@altendky In the future, consider submitting a PR. That way your name ends up on the commit.
