### ISSUE TITLE
PYSVN for centos/rhel 8

### ISSUE THREAD

**Issue by sumasri** [dsoprea/PySvn#152]
I'm trying to build pysvn package for el8 from source, where I was struck with the following error. I followed steps from docs(INSTALL.html).

[root@cu385 Source]# python setup.py configure 
Info: Configure for python 2.7.16 in exec_prefix /usr
Info: Found  PyCXX include in /usr/include/python2.7
Info: Found   PyCXX Source in /usr/share/python2.7/CXX
Info: Found    SVN include in /usr/include/subversion-1
Info: Found    SVN library in /usr/lib64
Info: Found        SVN bin in /usr/bin
Info: Found    APR include in /usr/include/apr-1
Info: Found    APR include in /usr/include/apr-1
Info: Found    APR library in /usr/lib64
Info: Building against SVN 1.10.2
Info: Found  PyCXX include in /usr/include/python2.7
Info: Found   PyCXX Source in /usr/share/python2.7/CXX
Info: Found    SVN include in /usr/include/subversion-1
Info: Found    SVN library in /usr/lib64
Info: Found        SVN bin in /usr/bin
Info: Found    APR include in /usr/include/apr-1
Info: Found    APR include in /usr/include/apr-1
Info: Found    APR library in /usr/lib64
Info: Building against SVN 1.10.2
Info: Using tool chain LinuxCompilerGCC
Info: Creating Makefile for Sources
Info: Creating Makefile for Tests
[root@cu385 Source]# make
make: Warning: File 'Makefile' has modification time 20082 s in the future
Compile: /usr/share/python2.7/CXX/cxxsupport.cxx into cxxsupport.o
In file included from /usr/share/python2.7/CXX/cxxsupport.cxx:37:
/usr/include/python2.7/CXX/WrapPython.h:58:10: fatal error: Python.h: No such file or directory
 #include <Python.h>
          ^~~~~~~~~~
compilation terminated.
make: *** [Makefile:155: cxxsupport.o] Error 1
[root@cu385 Source]#

**Comment by dsoprea** [comment]
You're doing too much.

See the top of the [documentation](https://github.com/dsoprea/pysvn#introduction). You need to install the Subversion tool ("svn") into your environment, and then this project will work. You shouldn't be calling "python setup.py configure" or passing any flags/options. "python setup.py install" or "python setup.py develop" as a privileged user (if not using virtualenv/etc..) will be enough.

If you don't need to do any actual development/contribution to PySVN, then just get PIP and run "pip install svn" (https://pypi.org/project/svn) as a privileged user.

**Comment by karthiksonti24** [comment]
I resolved this issue by uninstalling old python-devel and did fresh install.Then imported  PyCXX .
