### ISSUE TITLE
DeprecationWarning in common.py

### ISSUE THREAD

**Issue by gotakk** [dsoprea/PySvn#158]
Hi,

When I compile with this package, I have this warning : 
```
...................c:\users\XXX\appdata\local\programs\python\python38\lib\site-packages\svn\common.py:261: DeprecationWarning: This method will be removed in future versions.  Use 'list(elem)' or iteration over elem instead.
  entry_info = {x.tag: x.text for x in e.getchildren()}
```
https://github.com/dsoprea/PySvn/blob/e8a482d95bba2a3e153eb69c90209792d48e9aa8/svn/common.py#L261

OS : Windows 10
Python : Python 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:37:02) [MSC v.1924 64 bit (AMD64)] on win32
Pip : 20.2.3

**Comment by s1sfa** [comment]
Any chance to get this update into the pip release so everything works well on newer python versions.  .getchildren() was removed on python 3.9 release. 
https://docs.python.org/3/whatsnew/3.9.html
