### ISSUE TITLE
ValueError when URL not found

### ISSUE THREAD

**Issue by Dreamsorcerer** [dsoprea/PySvn#18]
When trying to access a RemoteClient on a non-existent repo, it throws a slightly odd ValueError. This would be easier to handle errors correctly if this threw a more specific SvnError or SvnUrlNotFoundError or similar.

import svn.remote
r = svn.remote.RemoteClient("https://plugins.svn.wordpress.org/gravityforms/trunk")
r.checkout("gravity")
> Traceback (most recent call last):
>  File "<stdin>", line 1, in <module>
>  File "/usr/local/lib/python3.4/dist-packages/svn/remote.py", line 20, in checkout
>    self.run_command('checkout', cmd)
>  File "/usr/local/lib/python3.4/dist-packages/svn/common.py", line 46, in run_command
>    (p.returncode, cmd, stdout))
>ValueError: Command failed with (1): ['svn', '--non-interactive', 'checkout', 'https://plugins.svn.wordpress.org/gravityforms/trunk', 'gravity']
>b"svn: E170000: URL 'https://plugins.svn.wordpress.org/gravityforms/trunk' doesn't exist\n"

**Comment by Dreamsorcerer** [comment]
Also just encountered this one while on a dodgy connection. This should produce a different exception to the previous case, maybe SvnConnectionError or similar:

ValueError: Command failed with (1): ['svn', '--non-interactive', 'ls', 'https://plugins.svn.wordpress.org/akismet/tags']
b"svn: E120108: Unable to connect to a repository at URL 'https://plugins.svn.wordpress.org/akismet/tags'\nsvn: E120108: Error running context: The server unexpectedly closed the connection.\n"

**Comment by dsoprea** [comment]
I'm going to close this. I expect that there's no good way to filter the connection-based errors from everything else. We simply throw a ValueError because the return-value from the SVN command is non-zero.

**Comment by Dreamsorcerer** [comment]
Well, it is showing the error messages in the trace, so I assumed you would have access to that information.

The use case, in using this library in a project, is that I want to handle a URL doesn't exist error, by asking the user to correct the URL. Whereas, a general connection error (as in the second case), means I should retry the connection a couple of times before aborting.

Even if you are unable to access this information, it should still not be a ValueError that is raised, this would indicate that the argument ("gravity") is an incorrect value, but it is completely valid. This would be appropriate, e.g. if the argument contained an invalid character for a svn branch.
As I suggested, a custom SvnError exception should be used, so a developer can catch these errors correctly. Gitpython does this reasonably well with a GitCommandError when a Git command returns a non-zero exit status. https://gitpython.readthedocs.io/en/stable/reference.html#git.exc.GitCommandError

"exception ValueError:
    Raised when a built-in operation or function receives an argument that has the right type but an inappropriate value, and the situation is not described by a more precise exception such as IndexError."
