### ISSUE TITLE
AttributeError: module 'pysvn' has no attribute 'Revision'

### ISSUE THREAD

**Issue by gkjolin** [dsoprea/PySvn#191]
import pysvn

 log_msgs = client.log(working_copy, discover_changed_paths=True,
                          revision_end=pysvn.Revision(pysvn.opt_revision_kind.number, last_patch_revision));

python 3.8

**Comment by dsoprea** [comment]
Wrong project.

https://sourceforge.net/projects/pysvn/

**Comment by dsoprea** [comment]
I'd also encourage you to include more description in the future. Since you're relying on cooperation, it'd be more polite.
