### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by gee-whiz** [dsoprea/PySvn#28]
warning: W000013: Can\'t open file \'/root/.subversion/servers\': Permission denied\n\n']

**Comment by dsoprea** [comment]
This is a file-permission issue on your local system. It's out of scope for a general library.

**Comment by gee-whiz** [comment]
ok thanks man I'll try to change file permision. just a quick question is there a way I can pass username and password

**Comment by dsoprea** [comment]
Do an update. You can pass "username" and "password" as optional arguments to either the constructor or utility constructor function.

**Comment by gee-whiz** [comment]
ok thanks a lot man
