### ISSUE TITLE
Accepting a self signed certificate.

### ISSUE THREAD

**Issue by encompass** [dsoprea/PySvn#30]
I think my PySvn is not working now due to a self signed certificate used on the svn server I am trying to connect to.  Is there a way to deal with accepting the certificate from pysvn itself.
My code works just fine when there is no self signed cert.

**Comment by encompass** [comment]
I tried accepting the self signed cert by doing a single co and accepted it permanently but it didn't see to have an affect on the issue. It sell doesn't accept the svn connection.

**Comment by dsoprea** [comment]
`pysvn` is just a wrapper around the commands. I searched for "subversion self signed certificate" in Google and found myself here: http://serverfault.com/questions/400093/run-svn-commands-with-self-signed-ssl-cert

So, the first thing you have to do is determine if you can get *svn* to work on it's own without involving `pysvn`: Based on that URL, make sure your hostname matches the CN in the certificate and pass the *--trust-server-cert* parameter. If that works, then we can add support for passing that parameter from *pysvn*.

**Comment by encompass** [comment]
Thanks.  I actually added support for --trust-server-cert just before you messaged, so it looks like we are on the right track.  With some time, I may bring it back to your code here.
The best way to handle the situation would be to some how throw an exception telling the situation so that it can be handled properly in code.

**Comment by encompass** [comment]
I also added support for defining the svn binary you want to use, as my my installation there are two versions. It's a similar feature and in common.py

**Comment by encompass** [comment]
Made a pull request...
https://github.com/dsoprea/PySvn/pull/31

**Comment by dsoprea** [comment]
Closing for lack of progress.
