### ISSUE TITLE
Server certificate verification failed

### ISSUE THREAD

**Issue by jamesduan** [dsoprea/PySvn#32]
my svn repository server need use username and password auth , but i can not found the parameter in the RemoteClient() function .

**Comment by dsoprea** [comment]
Pass "username" and "password" into the constructor. The README indicates this. Let me know if there's anything else.

**Comment by jamesduan** [comment]
![image](https://cloud.githubusercontent.com/assets/3363301/15346435/be56f376-1cea-11e6-8ca0-507909867b93.png)
this is my code ,  and return some error bellow.
![image](https://cloud.githubusercontent.com/assets/3363301/15346445/dfebbfe4-1cea-11e6-92e9-51f6c54f4b08.png)

**Comment by dsoprea** [comment]
You can't use *https* with an IP address. It verifies the hostname against
the common-name in the certificate.



Dustin

**Comment by dsoprea** [comment]
..Note that it mentions the issue in the error message. I recommend using
Google for basic connectivity issues. This is the wrong forum.
