### ISSUE TITLE
six version requirement

### ISSUE THREAD

**Issue by petef4** [dsoprea/PySvn#36]
I've just installed svn 0.3.38 on Python 2.7 using pip. It downgraded my version of six from 1.8.0 to 1.7.2. The current version on PyPI is 1.10.0.

Would you please consider changing requirements.txt to have six>=1.7.2

I have no immediate problem but if some other package makes the same call to use a fixed version of six then there could be a clash. The same goes for python-dateutil.

It is good for applications to use fixed versions in their requirements but libraries ought to be more flexible.

**Comment by dsoprea** [comment]
That's a bug. Fixed and uploaded.

**Comment by petef4** [comment]
I confirm that it is fixed, thanks for the swift response.

    pip install -U svn

Now I have svn-0.3.39, python-dateutil-2.2 and six-1.10.0.
