### ISSUE TITLE
Support for Diff

### ISSUE THREAD

**Issue by tusharmakkar08** [dsoprea/PySvn#40]
Hey

Can we make it to support `svn diff` ? 

Thanks

**Comment by dsoprea** [comment]
It's a very easy project to add additional functionality to. It'd be great if you could add the functionality yourself and submit a PR. 

Just look at one of the existing implemented commands in *common.py*. "svn diff" doesn't support XML output (only the diff-summary does, which we already do), but you can take the output parse the two sets of output, as well as the headers and body of each, and return. If you need help, me or someone else that's watching would be happy to support you.

**Comment by tusharmakkar08** [comment]
Cool. I will work on it and get back to you with a PR.

**Comment by tusharmakkar08** [comment]
@dsoprea : Submitted PR: https://github.com/dsoprea/PySvn/pull/46 for the same.

**Comment by tusharmakkar08** [comment]
@dsoprea : Closing since the PR https://github.com/dsoprea/PySvn/pull/48 is merged.
