### ISSUE TITLE
Please document that this is a wrapper for the CLI svn client

### ISSUE THREAD

**Issue by sybrenstuvel** [dsoprea/PySvn#42]
This library just wraps the `svn` commandline client, executing it using `subprocess`. In my opinion, this should be documented in the README, as it has implications for performance (each command needs to execute `svn`, which has to re-establish a HTTPS connection, etc.) as well as deployment (the machine the code runs on needs the `svn` CLI client).

**Comment by dsoprea** [comment]
If you add the footnote in a PR, I'll merge it.



Dustin
