### ISSUE TITLE
Unable to differentiate between SVN command failing and other errors

### ISSUE THREAD

**Issue by sybrenstuvel** [dsoprea/PySvn#45]
The library raises a `ValueError` when the SVN CLI client fails. This exception is very common, and can be raised for a number of reasons. As a result, it is difficult for the caller to distinguish between the SVN CLI client failing and other issues.

Please change the exception type, for example to a subclass of `ValueError` for backward compatibility. I've sent in a pull request (#43) for this.

**Comment by dsoprea** [comment]
Gonna close this. Go ahead and fix the merge conflicts in the PR and I'll merge.
