### ISSUE TITLE
Creation of Test Suite

### ISSUE THREAD

**Issue by tusharmakkar08** [dsoprea/PySvn#47]
Hey @dsoprea 

What do you think about forming a test suite for PySvn ? I can contribute for that if other maintainers can pitch in. 

Thanks

**Comment by dsoprea** [comment]
Definitely.

**Comment by tusharmakkar08** [comment]
Cool.

**Comment by tusharmakkar08** [comment]
@dsoprea I see that travis build is failing due to test cases. I am working on fixing them.

**Comment by dsoprea** [comment]
There was a command failure, which I fixed (might want to do an update).
Just take care of the test-case.

**Comment by dsoprea** [comment]
...Thanks for getting this going. Feel free to add a status-badge for
Travis to the top of the README.
