### ISSUE TITLE
Commit introduces tuple bug

### ISSUE THREAD

**Issue by dsoprea** [dsoprea/PySvn#55]
@tusharmakkar08 

PR #54 introduced bug:

Build:

https://travis-ci.org/dsoprea/PySvn/builds/159615353

Commit:

https://github.com/dsoprea/PySvn/commit/8fe6b8ba5387791062d806387050efff0f748ae2

**Comment by tusharmakkar08** [comment]
I am having a look at it. This is weird since [PR](https://travis-ci.org/dsoprea/PySvn/builds/159598873) was passing on travis.

**Comment by tusharmakkar08** [comment]
@dsoprea Ohh I see it's because of `line 61, in common.py` which was changed due to the SvnCommandError PR. I will fix this along with changes related to `SvnCommandError` converted to `SvnException`
