### ISSUE TITLE
Coveralls Integration

### ISSUE THREAD

**Issue by tusharmakkar08** [dsoprea/PySvn#63]
Hey @dsoprea 

I am planning to integrate [Coveralls](https://coveralls.io/) with this project. Let me know what you think about this. 

Thanks.

**Comment by dsoprea** [comment]
It'd be appreciated.

**Comment by tusharmakkar08** [comment]
Hey @dsoprea 

Since I don't have the collaborator access to the repo, you will have to go to the [Coveralls](https://coveralls.io/) page and activate it for the project. Also please update the settings correspondingly. Also let me know the embed link, so that I can add it in the `README.rst`. BTW current coverage is 64%. 

Thanks

**Comment by dsoprea** [comment]
Done.

**Comment by dsoprea** [comment]
```
[![Coverage Status](https://coveralls.io/repos/github/dsoprea/PySvn/badge.svg?branch=master)](https://coveralls.io/github/dsoprea/PySvn?branch=master)
```
