### ISSUE TITLE
Advantages over PySvn

### ISSUE THREAD

**Issue by tusharmakkar08** [dsoprea/PySvn#67]
Hey @dsoprea 

I was planning to add helpdoc in `README.md` or maybe host it via `github.io`, where we explain why our PySvn is better than [Pysvn](http://pysvn.tigris.org/). I searched for this because the earlier Pysvn which I was using causes a lot of issues while setting up. Some of the rants of developers facing issues are: 

- https://www.reddit.com/r/Python/comments/22q6gc/this_is_why_i_hate_pysvn/ 
- http://stackoverflow.com/a/25984096/1799475 

This would do 2 things: 

- It would make clear why to have our Pysvn when the old Pysvn is already there
- What benefits does our Pysvn provide over the old Pysvn

which would in-turn lead to more adaptability of our PySvn. What do you think about this?  

Thanks

**Comment by dsoprea** [comment]
If you feel compelled to add a blurb to README for marketing, submit a PR.
