### ISSUE TITLE
DNS resolution not working

### ISSUE THREAD

**Issue by verybadsoldier** [dsoprea/PySvn#69]
When I checkout using this library then this code in common.py returns an error:
```
p = subprocess.Popen(cmd,
                             stdout=subprocess.PIPE,
                             stderr=subprocess.STDOUT,
                             env={'LANG': 'en_US.UTF-8'})

 stdout = p.stdout.read()
     r = p.wait()
      if r != success_code:
         raise SvnException("Command failed with (%s): %s\n%s".format(
              (p.returncode, cmd, stdout)))
```

stdout contains:
`svn: E731001: Unable to connect to a repository at URL 'svn://dummydomain.corp/repos/testing/robot-
 framework-test/trunk'
svn: E731001: Unknown hostname 'dummydomain.corp'`

Invoking the very same command specified by 'cmd' manually in a shell works.

I think the problem is that the Popen call is using the parameter env and therefore effectively completely replacing the environment with the single variable 'LANG'.
I could fix the problem by just not using the env parameter:
`p = subprocess.Popen(cmd,
                             stdout=subprocess.PIPE,
                             stderr=subprocess.STDOUT)`

As a sidenote:
This does not produce a valid error string:
`raise SvnException("Command failed with (%s): %s\n%s".format(
                (p.returncode, cmd, stdout)))`
I think you cannot mix %s-syntax with format.

**Comment by daa** [comment]
Also I should note that sometimes it's required to set some environment variables for svn client to work, for example ``SVN_SSH``, and current full environment substitution prevents this.

**Comment by dsoprea** [comment]
It's unintentional. This was an oversight by the contributor.

**Comment by dsoprea** [comment]
Should be fixed.
