### ISSUE TITLE
shell environment gets wiped out in CommonClient.runCommand

### ISSUE THREAD

**Issue by cheecheeo** [dsoprea/PySvn#70]
https://github.com/dsoprea/PySvn/blob/master/svn/common.py#L55

This line sets the shell's environment to *only* LANG=...

It would be nice if the parent shell's environment could be preserved and only the LANG variable overwritten. As it is, this line makes `ssh-agent` unusable with this library.

**Comment by dsoprea** [comment]
Three people have brought this up in the last several hours, and no one has
submitted a PR to fix it. It was introduced by the PR of someone else who
was fixing a locale problem and I, nor anyway else, seemed to catch it. It
should be simple but I can't do it right now.

**Comment by tusharmakkar08** [comment]
@dsoprea I am working on it.
