### ISSUE TITLE
How to find that file is modified locally but not committed?

### ISSUE THREAD

**Issue by Alexander-Minyushkin** [dsoprea/PySvn#79]

**Comment by dsoprea** [comment]
It seems surreal to me that somehow, in the 156 commits and 2.5 years that this project has been alive, that neither me nor anyone else ever added a `status()` method. Holy crap.

This one is on me, guys. I'll try to get that in for you, in the next couple of days, unless someone else can beat me to a PR.

Thanks for bringing it up.

**Comment by dsoprea** [comment]
I added the functionality. Look at the test for more information as I've only added a brief mention in the documentation for now:

https://github.com/dsoprea/PySvn/blob/master/tests/test_common.py#L143

@tusharmakkar08 I added a complete implementation of how we should be setting-up and destroying a repository for a single test and implemented it for a test for the new `status` method:

https://github.com/dsoprea/PySvn/blob/master/tests/test_common.py#L43
https://github.com/dsoprea/PySvn/blob/master/tests/test_common.py#L68
https://github.com/dsoprea/PySvn/blob/master/tests/test_common.py#L78

**Comment by Alexander-Minyushkin** [comment]
Thanks for the fast reply!
In current version status report only locally modified items. 
I think it will be better to run **status** command with **-v** option to report all files. User will filter them later how he or she wants.

Here is extract from svn help:
>   **With no args, print only locally modified items (no network access).**
>   With -q, print only summary information about locally modified items.
>   With -u, add working revision and server out-of-date information.
>   **With -v, print full revision information on every item.**
>

**Comment by dsoprea** [comment]
I'll take a look in the next couple of days. If you don't want to wait then
I recommend you play with adding it yourself and submitting a PR.

**Comment by tusharmakkar08** [comment]
Hey @dsoprea 

Thanks for changing the tests. I was travelling since past couple of weeks and hence wasn't able to update it. 

Thanks.

**Comment by dsoprea** [comment]
I didn't change the functionality of the current tests. I refactored for
readability and then implemented a new test using a populated, ephemeral,
local repository.

Please refactoring the existing tests to do the same.

Dustin

**Comment by tusharmakkar08** [comment]
Cool. I will work on it.
