### ISSUE TITLE
Releasing a version with svn update and other nice, new features

### ISSUE THREAD

**Issue by drcraig** [dsoprea/PySvn#81]
Looks like you added support for svn update and other commands a couple weeks after the release of 0.3.44. Any plan to release these new features? They'd be really useful. For now, I can call run_command to do the svn update, but would prefer to do it the "right" way.

Thanks for writing this. It's incredibly nice to have a Python svn package that works in a virtualenv and doesn't need to be installed as a system package.

**Comment by dsoprea** [comment]
No problem. Standby.

**Comment by ocervell** [comment]
Up

**Comment by jrschneider** [comment]
+1

**Comment by dsoprea** [comment]
0.3.45 released. Thanks for your patience.
